Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: storage/uploads
  UploadServerUrl: http://127.0.0.1:8080/static
  UploadImageMaxSize: 5
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
Database:
  DBType: mysql
  Username: root
  Password: aaaaaa
  Host: 127.0.0.1:3306
  DBName: blog_service
  TablePrefix: blog_
  CharSet: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
JWT:
  Secret: aaaaaa
  Issuer: aaaaaa
  Expire: 7200
Email:
  Host: smtp.qq.com
  Port: 465
  UserName: xxxx@qq.com
  Password: xxxxx
  IsSSL: true
  From: xxxx@qq.com
  TO:
    - XXXXX@qq.com
